version: "3.1"
services:

    postgres:
      image: postgres:11.1-alpine
      container_name: om30-postgres
      working_dir: /application
      volumes:
        - ../:/application
      environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=admin
        - POSTGRES_DB=OM30
      ports:
        - "8084:5432"

    webserver:
      image: nginx:alpine
      container_name: om30-webserver
      working_dir: /application
      volumes:
          - ../:/application
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"

    php-fpm:
      build: ./php-fpm
      container_name: om30-php-fpm
      working_dir: /application
      volumes:
        - ../:/application
        - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

